branch-defaults:
  aws:
    environment: staging
environment-defaults:
  production:
    branch: null
    repository: null
global:
  application_name: apprenticeship-io
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:us-west-1::platform/Puma with Ruby 2.4
    running on 64bit Amazon Linux/2.6.0
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
